# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RandomGiphyGenerator' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RandomGiphyGenerator
  pod 'SwiftGifOrigin', '~> 1.6.1'
  pod 'Alamofire', '~> 4.5'
  pod 'AlamofireImage', '~> 3.3'
  pod 'AlamofireObjectMapper', '~> 4.0'

end
